#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — les réponses viennent de docs/declarations-magasins.md, qui les
# justifie une par une. Ce script ne décide rien : il déroule ce document dans
# l'ordre des deux formulaires, pour qu'on ne perde pas sa place au milieu.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=19
DOC="docs/declarations-magasins.md"

# ══ DEUX ENTRÉES ═══════════════════════════════════════════════════════════
#
#   scripts/declarations-magasins.sh            la première saisie (#321) :
#                                               Play, puis App Store
#   scripts/declarations-magasins.sh signaler   ce que la build qui signale
#                                               ajoute chez Play (#500)
#
# UNE ENTRÉE À PART, ET NON UNE QUESTION SUR LE CHEMIN DE LA PREMIÈRE SAISIE.
# Celle-ci ne change pas : qui la déroule de zéro avant la build qui signale
# déclare chez Play quatre types, et eux seuls, sans une question de plus qui
# lui ferait cocher les trois autres trop tôt. Et qui a déjà fait la première
# saisie n'a pas à la refaire pour ajouter ce que le point 9 ajoute.
#
# CE QUE SIGNALER AJOUTE EST DÉJÀ SAISI : le porteur l'a fait le 30 septembre
# 2026, corrigé et vérifié le même jour, en quatre exports. Trois erreurs
# avant la bonne : « Fichiers audio » → « Enregistrements audio ou vidéo »
# cochée, « Photos » décochée, « Partagées » cochée. `signaler` sert à le
# refaire plus tard, par exemple après une première saisie reprise de zéro :
# il nomme ces trois cases, et fait relire l'export par
# scripts/assert-play-data-safety.mjs, qui les voit toutes.

# pas "…" — une case à NE PAS cocher, en rouge, sous celles à cocher.
pas() { printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"; }

# facultatif_pour_signaler — les quatre réponses, les mêmes pour chacun des
# trois types que le signalement ajoute (point 9).
facultatif_pour_signaler() {
  step "Collectées ou partagées ?      →  Collectées"
  pas "Partagées                      →  ne pas cocher : rien n'est partagé"
  step "Traitées de façon éphémère ?   →  Non"
  step "Obligatoires ou facultatives ?"
  say "     →  Les utilisateurs peuvent choisir si ces données sont collectées ou non"
  step "Pourquoi sont-elles collectées ?"
  say "     ☑ Prévention des fraudes, sécurité et conformité"
  note "Une seule finalité. Facultatif : personne n'a à signaler pour se servir"
  note "de Messagr. Tranché le 30 septembre 2026, jugement 9."
}

# ══ PLAY CONSOLE, CE QUE SIGNALER AJOUTE (#500) ════════════════════════════
#
# Dans l'ordre du formulaire : « ID utilisateur » vient avant les trois types
# nouveaux, qui viennent avant « Contacts ».

saisie_signaler() {
  TOTAL_STAGES=9
  banner "Ce que signaler ajoute chez Play (#500)"

  stage "Play · signaler : une saisie à refaire"
  say "Ce qu'un signalement transmet se déclare en plus dans « Sécurité des"
  say "données » : le point 9 de $DOC,"
  say "tranché le 30 septembre 2026."
  say "Quand : au plus tard quand la build Android qui signale quitte la piste"
  say "de test interne."
  note "La section décrit « toutes les versions actuellement disponibles sur"
  note "Google Play », et Play ne demande pas d'y tenir les canaux de test internes."
  printf '\n'
  warn "C'est déjà fait : saisi le 30 septembre 2026, corrigé et vérifié le même jour."
  say "Cette entrée sert à le refaire plus tard, par exemple après une première"
  say "saisie reprise de zéro. Elle n'ajoute que ce qui change."
  note "App Store Connect ne change pas : chez Apple, le point 8 n'ajoute aucun type."
  pause "On refait la saisie ?"

  stage "Play · ouvrir « Sécurité des données »"
  open_url "https://play.google.com/console"
  step "Play Console → Messagr → « Contenu de l'application »."
  note "Dans la barre latérale : Monitor and improve → Policy and programmes → App content."
  step "Ligne « Sécurité des données » : ouvrir la déclaration."
  step "« Suivant » jusqu'à « Types de données »."
  note "« Collecte des données et sécurité » ne change pas : chiffrées en transit,"
  note "Oui ; suppression sur demande, Oui."
  pause "« Types de données » est ouvert ?"

  stage "Play · « Types de données » : trois de plus"
  say "Les quatre types de la première saisie restent cochés. Cocher EN PLUS"
  say "ces trois-là, et aucun autre :"
  step "Messages               →  Autres messages via une appli"
  step "Photos et vidéos       →  Photos"
  step "Fichiers et documents  →  Fichiers et documents"
  printf '\n'
  pas "Photos et vidéos       →  Vidéos"
  pas "Fichiers audio         →  aucune case, pas même « Enregistrements audio ou vidéo »"
  printf '\n'
  warn "Une case voisine cochée par mégarde, dans « Fichiers audio » : c'est la"
  warn "première des trois erreurs de la saisie du 30 septembre 2026. Relire de"
  warn "« Messages » à « Fichiers et documents » avant de continuer."
  note "Pas de vidéo : l'application n'en envoie pas, et une vidéo envoyée comme"
  note "fichier est un document. Pas d'audio : il n'y a pas de message vocal."
  pause "Les trois sont cochés en plus, et ni « Vidéos » ni « Fichiers audio » ?"

  stage "Play · « ID utilisateur » : une finalité de plus"
  step "« Suivant » : « Utilisation et traitement des données »."
  say "Les types y viennent dans l'ordre du formulaire. Le premier ne gagne"
  say "qu'une finalité :"
  step "Collectées, Non, Obligatoire   →  inchangés"
  step "Pourquoi sont-elles collectées ?"
  say "     ☑ Fonctionnement de l'application                 déjà cochée"
  say "     ☑ Gestion des comptes                             déjà cochée"
  say "     ☑ Prévention des fraudes, sécurité et conformité  À COCHER"
  note "Le service garde le compte qui signale jusqu'à douze mois après la"
  note "décision, et un signalement porte le compte visé."
  pause "« ID utilisateur » porte ses trois finalités ?"

  stage "Play · « Autres messages via une appli »"
  facultatif_pour_signaler
  note "Play : « Tous les autres types de messages. Par exemple, messages"
  note "instantanés ou contenus de chat. »"
  pause "« Autres messages via une appli » est rempli ?"

  stage "Play · « Photos »"
  facultatif_pour_signaler
  note "Play : « Photos d'un utilisateur. »"
  pause "« Photos » est rempli ?"

  stage "Play · « Fichiers et documents »"
  facultatif_pour_signaler
  note "Play : « Fichiers ou documents d'un utilisateur, ou informations sur ses"
  note "fichiers ou documents (noms de fichier, par exemple). » Le signalement"
  note "d'un document en porte le nom, le type, la taille et la clé."
  pause "« Fichiers et documents » est rempli ?"

  stage "Play · relire, enregistrer, envoyer"
  say "Rien d'autre ne change :"
  step "« Contacts », « Autres actions », « ID de l'appareil ou autres ID » : ne pas y toucher."
  printf '\n'
  step "Enregistrer."
  step "« Aperçu de la fiche Play Store » : relire ce que verra une personne."
  say "     sept types collectés, aucun partagé, aucune finalité publicitaire ;"
  say "     chiffrées en transit, oui ; suppression sur demande, oui."
  step "« Envoyer »."
  pause "La déclaration est envoyée ?"

  stage "Play · exporter le CSV, et le relire contre le document"
  step "En haut à droite de la page : « Exporter au format CSV »."
  ask EXPORT_PLAY "Chemin du CSV exporté :"
  EXPORT_PLAY="${EXPORT_PLAY/#\~/$HOME}"
  printf '\n'
  # Le contrôle lit ses réponses attendues dans les tableaux de $DOC : il dit
  # ce qui manque et ce qui est en trop, case par case.
  if node scripts/assert-play-data-safety.mjs "$EXPORT_PLAY"; then
    RELU="relu contre le document par scripts/assert-play-data-safety.mjs, sans écart"
    printf '\n'
    step "Le garder, daté, dans une PR :"
    say "  docs/declarations/play-securite-des-donnees-$(date +%Y-%m-%d).csv"
    note "C'est lui que la chaîne d'intégration relit ensuite contre $DOC."
  else
    RELU="relu contre le document : des écarts, à corriger dans la console"
    printf '\n'
    warn "L'export ne dit pas ce que dit le document. Corriger dans la console ce"
    warn "que la liste ci-dessus nomme, « Envoyer », exporter de nouveau, puis :"
    printf '\n      node scripts/assert-play-data-safety.mjs <nouvel export>\n\n'
    SKIPPED+=("corriger « Sécurité des données », puis relire le nouvel export")
  fi
  pause "On termine ?"

  finish

  # ── Le relevé de la saisie refaite ─────────────────────────────────────
  RECORD="/tmp/declarations-signaler-$(date +%Y%m%d-%H%M).md"
  # Les accents graves sont du Markdown, pour le ticket : rien à substituer.
  # shellcheck disable=SC2016
  {
    printf '## Ce que signaler ajoute chez Play, saisi de nouveau le %s\n\n' "$(date +%d/%m/%Y)"
    printf 'Saisie faite avec `scripts/declarations-magasins.sh signaler`, qui\n'
    printf 'déroule le point 9 de `%s`. Première saisie : le\n' "$DOC"
    printf '30 septembre 2026, corrigée et vérifiée le même jour.\n\n'
    printf '**Play, « Sécurité des données »** : trois types de plus, « Autres\n'
    printf 'messages via une appli », « Photos » et « Fichiers et documents »,\n'
    printf 'collectés, non partagés, non éphémères, facultatifs, pour la seule\n'
    printf 'finalité « Prévention des fraudes, sécurité et conformité ». « ID\n'
    printf 'utilisateur » gagne cette finalité et reste obligatoire. Ni « Vidéos »,\n'
    printf 'ni rien dans « Fichiers audio ».\n\n'
    printf "**Rien d'autre n'a changé** : « Contacts », « Autres actions »,\n"
    printf "« ID de l'appareil ou autres ID », chiffrement en transit « Oui »,\n"
    printf 'suppression « Oui ». Déclaration envoyée.\n\n'
    printf '**Export CSV** : %s.\n\n' "$RELU"
    printf '**App Store Connect, « App Privacy »** : rien, point 8.\n'
  } > "$RECORD"

  note "relevé écrit dans $RECORD"
  note "à coller dans #500 : gh issue comment 500 --body-file $RECORD"
  printf '\n'
}

case "${1:-}" in
  "") ;;
  signaler) saisie_signaler; exit 0 ;;
  *)
    printf 'usage : %s            la première saisie : Play, puis App Store (#321)\n' "$0" >&2
    printf '        %s signaler   ce que signaler ajoute chez Play (#500)\n' "$0" >&2
    exit 2
    ;;
esac

banner "Déclarations de confidentialité aux magasins (#321)"

# ══ PLAY CONSOLE ═══════════════════════════════════════════════════════════

stage "Play · ouvrir « Sécurité des données »"
say "Les réponses de ce formulaire sont écrites, question par question, dans"
say "$DOC. Gardez-le ouvert à côté."
open_url "https://play.google.com/console"
step "Play Console → Messagr → « Contenu de l'application »."
note "Dans la barre latérale : Monitor and improve → Policy and programmes → App content."
step "Ligne « Sécurité des données » → « Commencer »."
note "Le formulaire s'enregistre en brouillon : vous pouvez vous arrêter à tout moment."
pause "« Commencer » est cliqué ?"

stage "Play · étape « Collecte des données et sécurité »"
say "Trois questions. Les deux premières sont simples, la troisième demande un choix."
step "« L'application collecte-t-elle ou partage-t-elle l'un des types de données"
say "  utilisateur obligatoires ? »  →  OUI"
note "La page de confidentialité l'écrit : « le serveur conserve donc : … »."
printf '\n'
warn "« Toutes les données sont-elles chiffrées lors de leur transit ? »"
say "Le document dit OUI, mais il a été écrit avant la mesure du 16 septembre."
say "Le relais d'appel annonce encore turn: en clair, et 32 sessions authentifiées"
say "sur 45 y arrivent sans TLS, en portant l'identifiant du compte (#338)."
say ""
say "  • Répondre NON  : exact aujourd'hui. Une case négative visible sur la fiche,"
say "                    à corriger une fois #338 déployé."
say "  • Répondre OUI  : n'est vrai qu'après #338. À ne faire que si vous déployez"
say "                    le correctif du relais avant de soumettre."
ask TRANSIT "Qu'avez-vous répondu ? (oui / non)"
printf '\n'
step "« Proposez-vous un moyen de demander la suppression des données ? »  →  OUI"
note "Le lien de suppression de compte, si le formulaire le demande :"
note "https://messagr.eu/aide/#supprimer-votre-compte. La section existe depuis #333 ;"
note "à partir de la version qui porte le geste, elle le présente d'abord (#386)."
pause "Les trois questions sont répondues ?"

stage "Play · étape « Types de données »"
say "Cocher ces quatre-là, et AUCUN autre :"
step "Informations personnelles  →  ID utilisateur"
step "Contacts                   →  Contacts"
step "Activité dans les applis   →  Autres actions"
step "Appareil ou autres ID      →  Appareil ou autres ID"
printf '\n'
note "« Contacts » est le choix le plus inconfortable : sur la fiche il se lira"
note "« lit mon carnet d'adresses », ce qui est faux. Il est déclaré parce que Play"
note "vise nommément « les informations des graphes sociaux », et le serveur garde"
note "qui échange avec qui. Tranché le 16 septembre. Voir le jugement 3 du document."
pause "Les quatre types sont cochés, et eux seuls ?"

stage "Play · « ID utilisateur »"
say "Les mêmes quatre questions pour chaque type. Pour celui-ci :"
step "Collectées ou partagées ?      →  Collectées  (non partagées)"
step "Traitées de façon éphémère ?   →  Non"
step "Obligatoires ou facultatives ? →  Obligatoire"
step "Pourquoi sont-elles collectées ?"
say "     ☑ Fonctionnement de l'application"
say "     ☑ Gestion des comptes"
note "Non partagées : le serveur est hébergé par Hetzner, fournisseur de services."
pause "« ID utilisateur » est rempli ?"

stage "Play · « Contacts »"
step "Collectées ou partagées ?      →  Collectées"
step "Traitées de façon éphémère ?   →  Non"
step "Obligatoires ou facultatives ? →  Obligatoire"
step "Pourquoi sont-elles collectées ?"
say "     ☑ Fonctionnement de l'application"
say "     ☑ Prévention des fraudes, sécurité et conformité"
pause "« Contacts » est rempli ?"

stage "Play · « Autres actions »"
step "Collectées ou partagées ?      →  Collectées"
step "Traitées de façon éphémère ?   →  Non"
step "Obligatoires ou facultatives ? →  Obligatoire"
step "Pourquoi sont-elles collectées ?"
say "     ☑ Fonctionnement de l'application"
note "Une seule finalité pour ce type."
pause "« Autres actions » est rempli ?"

stage "Play · « Appareil ou autres ID »"
step "Collectées ou partagées ?      →  Collectées"
step "Traitées de façon éphémère ?   →  Non"
step "Obligatoires ou facultatives ? →  Obligatoire"
step "Pourquoi sont-elles collectées ?"
say "     ☑ Fonctionnement de l'application"
say "     ☑ Prévention des fraudes, sécurité et conformité"
printf '\n'
note "DEUX finalités et non une : les adresses IP sont à deux endroits pour deux"
note "raisons, la conservation qu'impose le décret et le relais d'appel, qui voit"
note "une adresse pour acheminer le son. Tranché le 16 septembre, jugement 2."
pause "« Appareil ou autres ID » est rempli ?"

stage "Play · relire et enregistrer"
step "Relire le récapitulatif : quatre types, aucun partagé, aucune finalité publicitaire."
step "Exporter le CSV et le garder : il fait foi de ce qui a été déclaré ce jour-là."
step "Enregistrer."
warn "Ne soumettez pas encore si vous avez répondu NON au chiffrement en transit"
warn "et comptez déployer #338 avant la mise en vente."
pause "Play est enregistré ?"

# ══ APP STORE CONNECT ══════════════════════════════════════════════════════

stage "App Store Connect · ouvrir « App Privacy »"
say "Rôle requis : Account Holder, Admin ou App Manager."
open_url "https://appstoreconnect.apple.com/apps/6809352505"
step "Barre latérale → « App Privacy » → « Get Started »."
step "« Do you or your third-party partners collect data from this app? »"
say "     →  Yes, we collect data from this app"
note "Firebase est un « third-party partner » au sens d'Apple, donc la réponse"
note "serait oui même si le serveur ne gardait rien."
step "« Next »."
pause "« Yes, we collect data » est validé ?"

stage "App Store Connect · cocher les types"
say "Six types, et aucun autre :"
step "Identifiers   →  User ID"
step "Identifiers   →  Device ID"
step "User Content  →  Emails or Text Messages"
step "Contacts      →  Contacts"
step "Usage Data    →  Other Usage Data"
step "Diagnostics   →  Other Diagnostic Data"
printf '\n'
note "PAS « Photos or Videos » ni « Other User Content » : un chiffré dont le serveur"
note "n'a pas la clé n'est pas conservé « in a readable form ». Tranché le 16 septembre,"
note "jugement 4. La note au relecteur, plus loin, désamorce la question d'avance."
step "« Save »."
pause "Les six types sont cochés ?"

stage "App Store Connect · « User ID »"
say "Trois réponses pour chaque type. Pour celui-ci :"
step "Data use            →  App Functionality"
step "Linked to the user  →  Yes"
step "Used for tracking   →  No"
note "Aucune autre finalité : ni Analytics, ni Product Personalization, ni publicité."
pause "« User ID » est rempli ?"

stage "App Store Connect · « Device ID »"
step "Data use            →  App Functionality"
step "Linked to the user  →  Yes"
step "Used for tracking   →  No"
note "Couvre les clés d'appareil, le jeton APNs que le serveur garde, les adresses IP,"
note "et l'identifiant d'installation Firebase."
pause "« Device ID » est rempli ?"

stage "App Store Connect · « Emails or Text Messages »"
step "Data use            →  App Functionality"
step "Linked to the user  →  Yes"
step "Used for tracking   →  No"
note "Ce qui est déclaré ici, c'est l'expéditeur et les destinataires, que le serveur"
note "lit. Pas le contenu, qu'il ne peut pas lire."
pause "« Emails or Text Messages » est rempli ?"

stage "App Store Connect · « Contacts »"
step "Data use            →  App Functionality"
step "Linked to the user  →  Yes"
step "Used for tracking   →  No"
pause "« Contacts » est rempli ?"

stage "App Store Connect · « Other Usage Data »"
step "Data use            →  App Functionality"
step "Linked to the user  →  Yes"
step "Used for tracking   →  No"
pause "« Other Usage Data » est rempli ?"

stage "App Store Connect · « Other Diagnostic Data »"
step "Data use            →  App Functionality"
warn "Linked to the user  →  NO"
say "  C'est le SEUL des six qui n'est pas lié. Il vient des manifestes des pods"
say "  Firebase, qui déclarent leur collecte comme non liée."
step "Used for tracking   →  No"
pause "« Other Diagnostic Data » est rempli ?"

stage "App Store Connect · les deux liens"
step "À côté de « Privacy Policy », cliquer « Edit »."
step "Privacy Policy URL  →  https://messagr.eu/confidentialite"
printf '\n'
step "« Privacy Choices URL »  →  https://messagr.eu/aide/#supprimer-votre-compte"
note "Apple la décrit comme « a webpage where users can access their data, request"
note "deletion, or make changes ». La section existe depuis #333 et dit comment"
note "demander la suppression ; elle présente le geste d'abord à partir de la version"
note "qui le porte (#386)."
printf '\n'
warn "« Any changes to the URLs release with your next app version. »"
pause "Les liens sont saisis ?"

stage "App Store Connect · la note au relecteur"
say "Elle désamorce la seule question probable en revue : pourquoi les photos ne"
say "sont pas déclarées. Son texte est la section PRIVACY de"
say "deploy/messagr-eu/app-store-listing/review-notes.txt, qui porte tout le"
say "champ « Notes » : l'entrée du relecteur la précède (#377)."
open_url "https://appstoreconnect.apple.com/apps/6809352505/distribution/ios/version/inflight"
step "Le champ se colle en entier, lien du relecteur compris, depuis l'étape"
say "  « La note au relecteur » de scripts/fiche-app-store.sh, qui remplit le lien."
step "Ne pas coller la seule section PRIVACY : elle remplacerait l'entrée du relecteur."
pause "La note est collée ?"

stage "App Store Connect · relire et publier"
step "« Product Page Preview » : relire l'étiquette telle que la verra une personne."
step "Vérifier qu'aucun type n'est marqué « Used to Track You »."
step "« Publish »."
warn "Publier ici publie l'étiquette de confidentialité, pas l'application."
pause "App Privacy est publié ?"

finish

# ── Le relevé de ce qui a été déclaré ──────────────────────────────────────
RECORD="/tmp/declarations-$(date +%Y%m%d-%H%M).md"
# Les accents graves sont du Markdown, pour le ticket : rien à substituer.
# shellcheck disable=SC2016
{
  printf '## Déclarations saisies dans les consoles, %s\n\n' "$(date +%d/%m/%Y)"
  printf 'Saisie faite avec `scripts/declarations-magasins.sh`, qui déroule\n'
  printf '`%s`.\n\n' "$DOC"
  printf '**Play, « Sécurité des données »** : quatre types déclarés (ID utilisateur,\n'
  printf 'Contacts, Autres actions, Appareil ou autres ID), aucun partagé, aucun\n'
  printf 'éphémère, tous obligatoires, aucune finalité publicitaire.\n\n'
  printf '**Chiffrement en transit** : répondu « %s ».\n\n' "$TRANSIT"
  printf '**App Store Connect, « App Privacy »** : six types déclarés, tous\n'
  printf '« App Functionality », tous liés sauf « Other Diagnostic Data », aucun\n'
  printf 'utilisé pour le suivi. « Privacy Choices URL » :\n'
  printf 'https://messagr.eu/aide/#supprimer-votre-compte (#333, #386).\n'
} > "$RECORD"

note "relevé écrit dans $RECORD"
note "à coller dans #321 : gh issue comment 321 --body-file $RECORD"
note "chez Play, ce que signaler ajoute se saisit à part : $0 signaler (#500)"
printf '\n'
