#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — les réponses viennent de docs/declarations-magasins.md, qui les
# justifie une par une. Ce script ne décide rien : il déroule ce document dans
# l'ordre des deux formulaires, pour qu'on ne perde pas sa place au milieu.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=19
DOC="docs/declarations-magasins.md"

banner "Déclarations de confidentialité aux magasins (#321)"

# ══ PLAY CONSOLE ═══════════════════════════════════════════════════════════

stage "Play · ouvrir « Sécurité des données »"
say "Les réponses de ce formulaire sont écrites, question par question, dans"
say "$DOC. Gardez-le ouvert à côté."
open_url "https://play.google.com/console"
step "Play Console → Messagr → « Contenu de l'application »."
note "Dans la barre latérale : Monitor and improve → Policy and programmes → App content."
step "Ligne « Sécurité des données » → « Commencer »."
note "Le formulaire s'enregistre en brouillon : vous pouvez vous arrêter à tout moment."
pause "« Commencer » est cliqué ?"

stage "Play · étape « Collecte des données et sécurité »"
say "Trois questions. Les deux premières sont simples, la troisième demande un choix."
step "« L'application collecte-t-elle ou partage-t-elle l'un des types de données"
say "  utilisateur obligatoires ? »  →  OUI"
note "La page de confidentialité l'écrit : « le serveur conserve donc : … »."
printf '\n'
warn "« Toutes les données sont-elles chiffrées lors de leur transit ? »"
say "Le document dit OUI, mais il a été écrit avant la mesure du 16 septembre."
say "Le relais d'appel annonce encore turn: en clair, et 32 sessions authentifiées"
say "sur 45 y arrivent sans TLS, en portant l'identifiant du compte (#338)."
say ""
say "  • Répondre NON  : exact aujourd'hui. Une case négative visible sur la fiche,"
say "                    à corriger une fois #338 déployé."
say "  • Répondre OUI  : n'est vrai qu'après #338. À ne faire que si vous déployez"
say "                    le correctif du relais avant de soumettre."
ask TRANSIT "Qu'avez-vous répondu ? (oui / non)"
printf '\n'
step "« Proposez-vous un moyen de demander la suppression des données ? »  →  OUI"
note "conformite@messagr.eu suffit à Play. Attention : l'exigence de suppression"
note "de COMPTE est une autre chose, et elle n'est pas remplie (#333)."
pause "Les trois questions sont répondues ?"

stage "Play · étape « Types de données »"
say "Cocher ces quatre-là, et AUCUN autre :"
step "Informations personnelles  →  ID utilisateur"
step "Contacts                   →  Contacts"
step "Activité dans les applis   →  Autres actions"
step "Appareil ou autres ID      →  Appareil ou autres ID"
printf '\n'
note "« Contacts » est le choix le plus inconfortable : sur la fiche il se lira"
note "« lit mon carnet d'adresses », ce qui est faux. Il est déclaré parce que Play"
note "vise nommément « les informations des graphes sociaux », et le serveur garde"
note "qui échange avec qui. Tranché le 16 septembre. Voir le jugement 3 du document."
pause "Les quatre types sont cochés, et eux seuls ?"

stage "Play · « ID utilisateur »"
say "Les mêmes quatre questions pour chaque type. Pour celui-ci :"
step "Collectées ou partagées ?      →  Collectées  (non partagées)"
step "Traitées de façon éphémère ?   →  Non"
step "Obligatoires ou facultatives ? →  Obligatoire"
step "Pourquoi sont-elles collectées ?"
say "     ☑ Fonctionnement de l'application"
say "     ☑ Gestion des comptes"
note "Non partagées : le serveur est hébergé par Hetzner, fournisseur de services."
pause "« ID utilisateur » est rempli ?"

stage "Play · « Contacts »"
step "Collectées ou partagées ?      →  Collectées"
step "Traitées de façon éphémère ?   →  Non"
step "Obligatoires ou facultatives ? →  Obligatoire"
step "Pourquoi sont-elles collectées ?"
say "     ☑ Fonctionnement de l'application"
say "     ☑ Prévention des fraudes, sécurité et conformité"
pause "« Contacts » est rempli ?"

stage "Play · « Autres actions »"
step "Collectées ou partagées ?      →  Collectées"
step "Traitées de façon éphémère ?   →  Non"
step "Obligatoires ou facultatives ? →  Obligatoire"
step "Pourquoi sont-elles collectées ?"
say "     ☑ Fonctionnement de l'application"
note "Une seule finalité pour ce type."
pause "« Autres actions » est rempli ?"

stage "Play · « Appareil ou autres ID »"
step "Collectées ou partagées ?      →  Collectées"
step "Traitées de façon éphémère ?   →  Non"
step "Obligatoires ou facultatives ? →  Obligatoire"
step "Pourquoi sont-elles collectées ?"
say "     ☑ Fonctionnement de l'application"
say "     ☑ Prévention des fraudes, sécurité et conformité"
printf '\n'
note "DEUX finalités et non une : les adresses IP sont à deux endroits pour deux"
note "raisons, la conservation qu'impose le décret et le relais d'appel, qui voit"
note "une adresse pour acheminer le son. Tranché le 16 septembre, jugement 2."
pause "« Appareil ou autres ID » est rempli ?"

stage "Play · relire et enregistrer"
step "Relire le récapitulatif : quatre types, aucun partagé, aucune finalité publicitaire."
step "Exporter le CSV et le garder : il fait foi de ce qui a été déclaré ce jour-là."
step "Enregistrer."
warn "Ne soumettez pas encore si vous avez répondu NON au chiffrement en transit"
warn "et comptez déployer #338 avant la mise en vente."
pause "Play est enregistré ?"

# ══ APP STORE CONNECT ══════════════════════════════════════════════════════

stage "App Store Connect · ouvrir « App Privacy »"
say "Rôle requis : Account Holder, Admin ou App Manager."
open_url "https://appstoreconnect.apple.com/apps/6809352505"
step "Barre latérale → « App Privacy » → « Get Started »."
step "« Do you or your third-party partners collect data from this app? »"
say "     →  Yes, we collect data from this app"
note "Firebase est un « third-party partner » au sens d'Apple, donc la réponse"
note "serait oui même si le serveur ne gardait rien."
step "« Next »."
pause "« Yes, we collect data » est validé ?"

stage "App Store Connect · cocher les types"
say "Six types, et aucun autre :"
step "Identifiers   →  User ID"
step "Identifiers   →  Device ID"
step "User Content  →  Emails or Text Messages"
step "Contacts      →  Contacts"
step "Usage Data    →  Other Usage Data"
step "Diagnostics   →  Other Diagnostic Data"
printf '\n'
note "PAS « Photos or Videos » ni « Other User Content » : un chiffré dont le serveur"
note "n'a pas la clé n'est pas conservé « in a readable form ». Tranché le 16 septembre,"
note "jugement 4. La note au relecteur, plus loin, désamorce la question d'avance."
step "« Save »."
pause "Les six types sont cochés ?"

stage "App Store Connect · « User ID »"
say "Trois réponses pour chaque type. Pour celui-ci :"
step "Data use            →  App Functionality"
step "Linked to the user  →  Yes"
step "Used for tracking   →  No"
note "Aucune autre finalité : ni Analytics, ni Product Personalization, ni publicité."
pause "« User ID » est rempli ?"

stage "App Store Connect · « Device ID »"
step "Data use            →  App Functionality"
step "Linked to the user  →  Yes"
step "Used for tracking   →  No"
note "Couvre les clés d'appareil, le jeton APNs que le serveur garde, les adresses IP,"
note "et l'identifiant d'installation Firebase."
pause "« Device ID » est rempli ?"

stage "App Store Connect · « Emails or Text Messages »"
step "Data use            →  App Functionality"
step "Linked to the user  →  Yes"
step "Used for tracking   →  No"
note "Ce qui est déclaré ici, c'est l'expéditeur et les destinataires, que le serveur"
note "lit. Pas le contenu, qu'il ne peut pas lire."
pause "« Emails or Text Messages » est rempli ?"

stage "App Store Connect · « Contacts »"
step "Data use            →  App Functionality"
step "Linked to the user  →  Yes"
step "Used for tracking   →  No"
pause "« Contacts » est rempli ?"

stage "App Store Connect · « Other Usage Data »"
step "Data use            →  App Functionality"
step "Linked to the user  →  Yes"
step "Used for tracking   →  No"
pause "« Other Usage Data » est rempli ?"

stage "App Store Connect · « Other Diagnostic Data »"
step "Data use            →  App Functionality"
warn "Linked to the user  →  NO"
say "  C'est le SEUL des six qui n'est pas lié. Il vient des manifestes des pods"
say "  Firebase, qui déclarent leur collecte comme non liée."
step "Used for tracking   →  No"
pause "« Other Diagnostic Data » est rempli ?"

stage "App Store Connect · les deux liens"
step "À côté de « Privacy Policy », cliquer « Edit »."
step "Privacy Policy URL  →  https://messagr.eu/confidentialite"
printf '\n'
step "« Privacy Choices URL »  →  LAISSER VIDE"
note "Apple la décrit comme « a webpage where users can access their data, request"
note "deletion, or make changes ». La page n'a pas encore de section de suppression"
note "qu'un lien puisse viser : c'est #333. Y mettre la page entière serait faux."
printf '\n'
warn "« Any changes to the URLs release with your next app version. »"
pause "Les liens sont saisis ?"

stage "App Store Connect · la note au relecteur"
say "Elle désamorce la seule question probable en revue : pourquoi les photos ne"
say "sont pas déclarées. Son texte est dans $DOC,"
say "section « La note au relecteur d'App Store Connect »."
open_url "https://appstoreconnect.apple.com/apps/6809352505/distribution/ios/version/inflight"
step "TestFlight ou la version → « App Review Information » → « Notes »."
step "Coller la note en entier, sans la raccourcir : elle cite la définition d'Apple"
say "  et l'adresse publique du document, ce qui est ce qui la rend vérifiable."
pause "La note est collée ?"

stage "App Store Connect · relire et publier"
step "« Product Page Preview » : relire l'étiquette telle que la verra une personne."
step "Vérifier qu'aucun type n'est marqué « Used to Track You »."
step "« Publish »."
warn "Publier ici publie l'étiquette de confidentialité, pas l'application."
pause "App Privacy est publié ?"

finish

# ── Le relevé de ce qui a été déclaré ──────────────────────────────────────
RECORD="/tmp/declarations-$(date +%Y%m%d-%H%M).md"
{
  printf '## Déclarations saisies dans les consoles, %s\n\n' "$(date +%d/%m/%Y)"
  printf 'Saisie faite avec `scripts/declarations-magasins.sh`, qui déroule\n'
  printf '`%s`.\n\n' "$DOC"
  printf '**Play, « Sécurité des données »** : quatre types déclarés (ID utilisateur,\n'
  printf 'Contacts, Autres actions, Appareil ou autres ID), aucun partagé, aucun\n'
  printf 'éphémère, tous obligatoires, aucune finalité publicitaire.\n\n'
  printf '**Chiffrement en transit** : répondu « %s ».\n\n' "$TRANSIT"
  printf '**App Store Connect, « App Privacy »** : six types déclarés, tous\n'
  printf '« App Functionality », tous liés sauf « Other Diagnostic Data », aucun\n'
  printf 'utilisé pour le suivi. « Privacy Choices URL » laissée vide (#333).\n'
} > "$RECORD"

note "relevé écrit dans $RECORD"
note "à coller dans #321 : gh issue comment 321 --body-file $RECORD"
printf '\n'
