#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — les valeurs sont LUES dans le dépôt, jamais recopiées ici. Si
# `fr-FR.json` change, cet assistant dit la nouvelle valeur au tour suivant.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
APP_ID=6809352505
FICHE="deploy/messagr-eu/app-store-listing/fr-FR.json"
DOC="docs/declarations-magasins.md"
CAPTURES="${MESSAGR_CAPTURES_DIR:-$PWD/captures-store}"

# champ <clé> — sort la valeur du dépôt, sans jamais l'inventer.
champ() {
  python3 -c "import json,sys; print(json.load(open('$FICHE'))['$1'])" 2>/dev/null \
    || { warn "impossible de lire $1 dans $FICHE"; return 1; }
}

# montrer <clé> <libellé> — affiche la valeur et sa longueur.
montrer() {
  local v; v=$(champ "$1") || return
  printf '  %s%s%s (%s caractères)\n' "$BOLD" "$2" "$RESET" "${#v}"
  printf '\n%s\n\n' "$v"
}

banner "La fiche App Store de Messagr (#350)"

stage "Avant tout : d'où viennent ces valeurs"
say "Rien n'est à inventer. Les six champs sont écrits dans le dépôt :"
step "$FICHE"
note "Chaque limite d'Apple y est tenue par deploy/messagr-eu/app-store-listing/check.py,"
note "qui tourne sur chaque PR. Les mots-clés sont comptés en OCTETS, pas en caractères."
printf '\n'
say "Trois blocages sont déjà levés de votre côté : la case « Connexion requise »"
say "décochée, la tarification, et les droits relatifs au contenu."
printf '\n'
warn "Ce qui suit modifie une fiche publique. Rien n'est envoyé par cet assistant :"
warn "il ouvre les pages et vous dit quoi coller."
pause "On y va ?"

stage "Les captures d'écran, produites par le dépôt"
say "Deux fichiers, aux deux tailles d'iPhone qu'Apple accepte. La V1 ne"
say "revendique pas l'iPad, donc sa capture n'est plus exigée."
printf '\n'
step "Lancez, depuis la racine du dépôt :"
printf '\n      ./scripts/capture-ios-store-screenshots.sh %s\n\n' "$CAPTURES"
note "Cinq minutes. Il fabrique ses simulateurs, photographie l'application,"
note "et les supprime. Il ne construit rien : il réutilise la build Release"
note "déjà posée, et refuse en redonnant la commande si elle manque."
printf '\n'
warn "Regardez les fichiers avant de les téléverser."
say "  Une bannière d'Apple s'est déjà glissée en travers d'une capture,"
say "  et tous les contrôles en aval disaient oui."
pause "Les captures sont produites et regardées ?"

stage "Téléverser les captures"
open_url "https://appstoreconnect.apple.com/apps/$APP_ID/distribution/ios/version/inflight"
step "Section « Aperçus et captures d'écran », onglet de langue « Français »."
step "Choisir la taille « iPhone 6,9\" », déposer le fichier qui porte 6.9 dans son nom."
step "Choisir « iPhone 6,5\" », déposer celui qui porte 6.5."
note "Si la console n'affiche pas les deux tailles, une seule suffit :"
note "elle met l'autre à l'échelle. La règle est « Required if app runs on"
note "iPhone and screenshots for 6.9\" display aren't provided »."
pause "Les captures sont téléversées ?"

stage "La description"
say "À coller dans « Description », onglet Français."
montrer description "Description"
note "Deux écarts avec la fiche Play, imposés par Apple : la section des"
note "notifications ne nomme plus Android ni Firebase (guideline 2.3.10), et"
note "« distribuée à un petit nombre de testeurs » est retirée (guideline 2.2,"
note "« Demos, betas, and trial versions don't belong on the App Store »)."
pause "La description est collée ?"

stage "Les mots-clés"
montrer keywords "Mots-clés"
warn "La limite est de 100 OCTETS, pas 100 caractères."
note "Cette liste fait 93 octets pour 87 caractères : le français est accentué."
note "N'y ajoutez rien sans relancer check.py, qui compte les octets."
printf '\n'
note "Apple ignore le nom de l'application et les mots du titre : ils n'y sont pas."
pause "Les mots-clés sont collés ?"

stage "Le texte promotionnel et le sous-titre"
montrer subtitle "Sous-titre"
montrer promotionalText "Texte promotionnel"
note "Le texte promotionnel se modifie sans nouvelle soumission, contrairement"
note "au reste. C'est pourquoi il porte le renvoi daté plutôt qu'une promesse."
pause "Les deux sont collés ?"

stage "Les trois adresses et le copyright"
montrer supportUrl "URL de l'assistance"
say "  Cette page existe depuis aujourd'hui et répond 200. Elle dit à qui"
say "  écrire et comment supprimer son compte."
printf '\n'
montrer marketingUrl "URL marketing"
montrer copyright "Copyright"
printf '\n'
warn "« Privacy Choices URL » : LAISSER VIDE n'est plus la bonne réponse."
say "  Elle peut recevoir https://messagr.eu/aide/#supprimer-votre-compte,"
say "  qu'Apple décrit comme « a webpage where users can request deletion »."
pause "Les adresses et le copyright sont saisis ?"

stage "La note au relecteur"
say "Elle désamorce la seule question probable en revue : pourquoi les photos"
say "ne sont pas déclarées alors que l'application en envoie."
printf '\n'
step "Son texte est dans $DOC,"
step "section « La note au relecteur d'App Store Connect »."
printf '\n'
step "Dans la console : « Informations de vérification » → « Notes »."
step "Coller la note EN ENTIER, sans la raccourcir."
note "Elle cite la définition d'Apple et l'adresse publique du document."
note "C'est ce qui la rend vérifiable plutôt que plaidante."
printf '\n'
warn "« Connexion requise » doit rester DÉCOCHÉE."
say "  On n'entre dans Messagr que par invitation : il n'y a ni identifiant"
say "  ni mot de passe à confier. Tout passe par cette note."
pause "La note est collée ?"

stage "Relire, puis soumettre"
step "Relire la page : plus aucun bandeau rouge en haut."
step "« Aperçu de la page produit » : regarder ce que verra une personne."
step "Vérifier qu'aucun type n'est marqué « Used to Track You »."
printf '\n'
step "Puis « Ajouter pour vérification »."
printf '\n'
warn "La build que le relecteur recevra doit être sur TestFlight."
say "  La dernière publiée est la 139, du 16 septembre, sur la piste interne"
say "  Play. Côté iOS, vérifiez quelle build est attachée à cette version."
pause "Soumis ?"

finish

RECORD="/tmp/fiche-app-store-$(date +%Y%m%d-%H%M).md"
{
  printf '## Fiche App Store saisie, %s\n\n' "$(date +%d/%m/%Y)"
  printf 'Saisie faite avec `scripts/fiche-app-store.sh`, qui lit\n'
  printf '`%s`.\n\n' "$FICHE"
  printf '| Champ | Valeur |\n| --- | --- |\n'
  for k in name subtitle keywords supportUrl marketingUrl copyright; do
    printf '| `%s` | %s |\n' "$k" "$(champ "$k")"
  done
  printf '\nDescription et texte promotionnel : tels que le dépôt les porte.\n'
  printf '\nCaptures : deux classes d.iPhone. L.iPad n.est pas revendique par la V1.\n'
} > "$RECORD"
note "relevé écrit dans $RECORD"
note "à poser sur le ticket : gh issue comment 350 --body-file $RECORD"
printf '\n'
