#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

# NOTHING THIS WIZARD CAPTURES IS WRITTEN TO A FILE IN THIS REPOSITORY.
#
# The library's write_env exists for values a developer keeps locally. Every
# value here is either a password or a signing key, and the whole arrangement
# depends on them living in the GitHub secret store and nowhere else. So
# write_env is never called, and ENV_FILE is pointed outside the tree so that
# an accidental call could not land one here either.
ENV_FILE="${TMPDIR:-/tmp}/messagr-play-wizard.env"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# The key this project already has, recovered from the previous repository's
# setup: RSA 4096, valid to 2053. Minting a second one would be a different
# application identity for no reason, so the default points at the one that
# exists rather than at a name a fresh run would invent.
KEYSTORE_PATH="${MESSAGR_UPLOAD_KEYSTORE:-$HOME/.messagr-signature/messagr-distribution.jks}"

banner "Messagr: publishing to Play"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "The tools this needs"
say "Nothing is created yet. This only checks that the next ten stages can work."
missing=0
for tool in gh keytool base64 unzip; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
  else
    printf '  %s✗%s %s is missing\n' "$RED" "$RESET" "$tool"
    missing=1
  fi
done
if ! gh auth status >/dev/null 2>&1; then
  warn "gh is not authenticated. Run: gh auth login"
  missing=1
else
  printf '  %s✓%s gh is authenticated as %s\n' "$GREEN" "$RESET" "$(gh api user --jq .login 2>/dev/null || echo '?')"
fi
if [[ "$missing" -ne 0 ]]; then
  warn "Fix the above and re-run. Nothing has been changed."
  exit 1
fi
note "keytool comes with the JDK; on macOS, 'brew install temurin' provides one."
pause "All present. Continue?"

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "Create the application on Play"
say "The listing has to exist before a key can be registered against it."
open_url "https://play.google.com/console/developers"
step "Click 'Create app'."
step "App name: Messagr. Default language: French. Type: App. Free."
step "Package name, when Play asks for it: eu.messagr — the reverse-DNS of messagr.eu, and permanent."
step "Accept the developer programme and export law declarations."
step "Once created, open 'Setup → App integrity → App signing'."
note "A new application is enrolled in Play App Signing automatically: Google"
note "generates and holds the app signing key. That is the key whose loss would"
note "end the application, and this is why you will never hold a copy of it."
confirm "Does the App signing page show that Google holds the app signing key?" \
  || warn "Continue anyway, but check this before the first release: without it, the upload key below is the app signing key, permanently."
pause "Continue?"

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "The upload key"
say "One already exists at ~/.messagr-signature, from the previous repository's"
say "setup: RSA 4096, valid to 2053, which is well past Play's 2033 floor."
say "Its four secrets are already set on this repository."
note "This stage only mints one if that key is gone."
say ""
say "Keystore file: $KEYSTORE_PATH"
if [[ -f "$KEYSTORE_PATH" ]]; then
  warn "A keystore already exists at that path."
  note "Re-using it is correct if it is the one Play knows. Overwriting it would"
  note "orphan every build Play has accepted from it."
  if confirm "Re-use the existing keystore?"; then
    ask UPLOAD_ALIAS "Alias inside that keystore:"
  else
    warn "Move the existing file aside first, then re-run. Nothing was changed."
    exit 1
  fi
else
  ask UPLOAD_ALIAS "Alias for the key [messagr-upload]:"
  [[ -z "$UPLOAD_ALIAS" ]] && UPLOAD_ALIAS="messagr-upload"
  say ""
  step "keytool will ask for a password twice, then for a name and organisation."
  step "The name fields are cosmetic here; the passwords are not."
  note "-validity 10000 is Play's own requirement: a key expiring before 2033-10-22 is refused."
  note "4096 rather than the commonly copied 2048, since this is trusted for a decade."
  pause "Run keytool now?"
  keytool -genkeypair -v \
    -keystore "$KEYSTORE_PATH" \
    -alias "$UPLOAD_ALIAS" \
    -keyalg RSA -keysize 4096 -validity 10000
  chmod 600 "$KEYSTORE_PATH"
fi
say ""
ask_secret UPLOAD_STORE_PASSWORD "Keystore password (what you just typed):"
ask_secret UPLOAD_KEY_PASSWORD "Key password (Enter if you reused the keystore password):"
[[ -z "$UPLOAD_KEY_PASSWORD" ]] && UPLOAD_KEY_PASSWORD="$UPLOAD_STORE_PASSWORD"

# Proven before it is trusted: a password typed wrongly here would otherwise
# surface as a build failure several stages later.
if keytool -list -keystore "$KEYSTORE_PATH" -alias "$UPLOAD_ALIAS" \
     -storepass "$UPLOAD_STORE_PASSWORD" >/dev/null 2>&1; then
  printf '  %s✓%s the keystore opens with that password\n' "$GREEN" "$RESET"
else
  warn "The keystore did not open with that password or that alias. Re-run this stage."
  exit 1
fi
warn "Back up $KEYSTORE_PATH somewhere that survives this machine."
note "Losing it is recoverable (docs/publishing-android.md), but it costs days."
pause "Backed up. Continue?"

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "Hand the upload key to continuous integration"
say "Four secrets, set on this repository. None of them touches a file here."
if gh secret list 2>/dev/null | grep -q MESSAGR_UPLOAD_KEYSTORE_BASE64; then
  note "They are already set. Re-setting them is harmless and idempotent."
  confirm "Set them again anyway?" || { pause "Skipped. Continue?"; SKIP_SECRETS=1; }
fi
if [[ "${SKIP_SECRETS:-0}" != "1" ]]; then
UPLOAD_KEYSTORE_BASE64="$(base64 < "$KEYSTORE_PATH" | tr -d '\n')"
set_secret MESSAGR_UPLOAD_KEYSTORE_BASE64 "$UPLOAD_KEYSTORE_BASE64"
set_secret MESSAGR_UPLOAD_KEYSTORE_PASSWORD "$UPLOAD_STORE_PASSWORD"
set_secret MESSAGR_UPLOAD_KEY_ALIAS "$UPLOAD_ALIAS"
set_secret MESSAGR_UPLOAD_KEY_PASSWORD "$UPLOAD_KEY_PASSWORD"
unset UPLOAD_KEYSTORE_BASE64
fi
pause "Continue?"

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "Create the service account that will upload"
say "This is what lets the Publish workflow talk to Play without a person."
open_url "https://console.cloud.google.com/apis/library/androidpublisher.googleapis.com"
step "Pick or create a Google Cloud project, then click 'Enable' on the Google Play Android Developer API."
note "Linking that project to your developer account is no longer required."
pause "API enabled. Continue?"
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts"
step "Click 'Create service account'. Name it messagr-publisher."
step "Skip the optional roles: the permission that matters is granted in Play, not here."
step "Open the account → Keys → Add key → Create new key → JSON. It downloads."
say ""
ask SERVICE_ACCOUNT_EMAIL "Paste the service account email (…iam.gserviceaccount.com):"
ask SERVICE_ACCOUNT_JSON_PATH "Path to the downloaded JSON key:"
SERVICE_ACCOUNT_JSON_PATH="${SERVICE_ACCOUNT_JSON_PATH/#\~/$HOME}"
if [[ ! -f "$SERVICE_ACCOUNT_JSON_PATH" ]]; then
  warn "No file at that path. Re-run this stage."
  exit 1
fi
printf '  %s✓%s found the key file\n' "$GREEN" "$RESET"
pause "Continue?"

# ── 6 ──────────────────────────────────────────────────────────────────────
stage "Let that account release to testing tracks"
say "Created in Google Cloud, but it can do nothing until Play grants it something."
open_url "https://play.google.com/console/developers/users-and-permissions"
step "Click 'Invite new users'."
step "Email address: $SERVICE_ACCOUNT_EMAIL"
step "Under 'App permissions', add Messagr."
step "Grant: 'Release to testing tracks' and 'View app information'."
warn "Do not grant production release rights. This account only needs the internal track."
pause "Invited and granted. Continue?"

# ── 7 ──────────────────────────────────────────────────────────────────────
stage "Hand the service account to continuous integration"
set_secret MESSAGR_PLAY_SERVICE_ACCOUNT_JSON "$(cat "$SERVICE_ACCOUNT_JSON_PATH")"
say ""
warn "Delete the downloaded JSON key now: it is a credential, and it is in your Downloads folder."
note "  rm '$SERVICE_ACCOUNT_JSON_PATH'"
pause "Continue?"

# ── 8 ──────────────────────────────────────────────────────────────────────
stage "Build a signed bundle, before touching Play"
say "Deliberately before the upload: a key that does not work should fail here,"
say "not after you have filled in four declaration forms."
pause "Build now? This takes a few minutes."
(
  cd "$REPO_ROOT/packages/app/android"
  MESSAGR_UPLOAD_KEYSTORE="$KEYSTORE_PATH" \
  MESSAGR_UPLOAD_KEYSTORE_PASSWORD="$UPLOAD_STORE_PASSWORD" \
  MESSAGR_UPLOAD_KEY_ALIAS="$UPLOAD_ALIAS" \
  MESSAGR_UPLOAD_KEY_PASSWORD="$UPLOAD_KEY_PASSWORD" \
  ./gradlew :app:bundleRelease
)
BUNDLE="$REPO_ROOT/packages/app/android/app/build/outputs/bundle/release/app-release.aab"

# ASKED OF JARSIGNER, AND WITHOUT A PIPE.
#
# This looked for a `META-INF/*.RSA` entry with `unzip -l | grep -q`, and it
# was wrong twice over.
#
# `grep -q` stops at its first match and closes the pipe. `unzip`, still
# listing thousands of entries from an eighty-megabyte archive, then dies of
# SIGPIPE -- and `set -o pipefail` turns that into a failed pipeline even
# though the match was found. Measured: two runs in six. So a perfectly
# signed bundle was called unsigned about a third of the time, which is worse
# than always failing.
#
# And the entry name was only ever a proxy. `jarsigner` answers the actual
# question. Its exit status does not: it returns 0 for an unsigned jar too,
# so the verdict is read from what it says, with `case` rather than another
# pipe.
verdict="$(jarsigner -verify "$BUNDLE" 2>&1 || true)"
case "$verdict" in
  *"jar verified"*)
    printf '  %s✓%s the bundle is signed: %s\n' "$GREEN" "$RESET" "$BUNDLE"
    ;;
  *)
    warn "The bundle is not signed. The key did not reach gradle."
    note "jarsigner said: ${verdict%%$'\n'*}"
    exit 1
    ;;
esac
pause "Continue?"

# ── 9 ──────────────────────────────────────────────────────────────────────
stage "The first release, by hand"
say "Only this one. Every upload after it is the Publish workflow's."
note "Not because the API refuses a first release, which Google does not say"
note "either way, but because a release cannot go out until the declarations"
note "below are filled in, and the API fills in none of them."
open_url "https://play.google.com/console/developers"
step "Messagr → Testing → Internal testing → Create new release."
step "Upload: $BUNDLE"
step "Release name and notes: anything. This build is a diagnostic screen."
step "Then work through the red items in 'Dashboard': store listing, content rating, data safety, target audience."
warn "Data safety: this application sends no analytics and collects no data. Answer accordingly."
pause "Release rolled out to internal testing. Continue?"

# ── 10 ─────────────────────────────────────────────────────────────────────
stage "Install it on a device"
say "This is the criterion the ticket actually turns on: the path proven, end to end."
step "Internal testing → Testers → add your own Google account to a tester list."
step "Copy the 'Copy link' opt-in URL and open it on the phone."
step "Accept the invitation, then install from the Play Store."
warn "The application will show a diagnostic readout. That is what it is meant to show:"
note "this proves the distribution path, not the product."
confirm "Did it install and open on a real device?" \
  || warn "That is the one thing this wizard cannot do for you. #43 stays open until it does."
pause "Continue?"

# ── 11 ─────────────────────────────────────────────────────────────────────
stage "Prove the automated path"
say "The second upload should need no browser at all."
open_url "https://github.com/mmaudet/messagr/actions/workflows/publish.yml"
step "Run workflow → track: internal."
note "It refuses by name if a secret is missing, and asserts the signature itself"
note "before uploading, rather than letting Play be the one to notice."
confirm "Did the workflow reach the internal track on its own?" \
  || SKIPPED+=("re-run Actions → Publish once the first release is live")

finish
